" setup vim-plug
source ~/.vim/setup_vim-plug.vim

" add a colorscheme is a gui is running
" colorscheme monokai
colorscheme seoul256
if has('gui_running')
    " remove the menu bar
    set guioptions-=m
    " remove the tool bar
    set guioptions-=T

    if has('gui_win32')
        set guifont=Consolas:h10
    endif
endif

" vim-easy-align options
source ~/.vim/setup_vim-easy-align.vim

" setup lightline
source ~/.vim/setup_lightline.vim

" setup python
source ~/.vim/setup_python-mode.vim

" setup nerdtree git
source ~/.vim/setup_nerdtree-git-plugin.vim

" settings for scratc vim
"source ~/vimfiles/setup_scratch.vim
source ~/.vim/setup_vim-notes.vim

" misc options
source ~/.vim/setup_misc.vim
